// Install photos, by slot. Generated by scripts/import-photos.py from
// "install-photos/" — don't edit by hand.
// A slot that's missing falls back to the styled camera-feed panel.
export type Photo = { webp: string; jpg: string };

export const PHOTOS: Partial<Record<"hero" | "residential" | "commercial" | "construction" | "farm" | "solar-cam", Photo>> = {
};
