"""Import install photos into the site.

Reads "install-photos/<slot>.<jpg|jpeg|png|heic|webp>",
writes web-sized copies to assets/photos/<slot>.webp + .jpg (1600px wide),
and regenerates src/lib/photos.ts so the pages pick them up.

Usage: python3 scripts/import-photos.py
"""
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "install-photos"
OUT = ROOT / "assets" / "photos"
MANIFEST = ROOT / "src" / "lib" / "photos.ts"
SLOTS = ["hero", "residential", "commercial", "construction", "farm", "solar-cam"]
EXTS = [".jpg", ".jpeg", ".png", ".heic", ".webp", ".JPG", ".JPEG", ".PNG", ".HEIC", ".WEBP"]


def find(slot):
    for ext in EXTS:
        p = SRC / f"{slot}{ext}"
        if p.exists():
            return p
    return None


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    found = []
    for slot in SLOTS:
        src = find(slot)
        if not src:
            continue
        jpg = OUT / f"{slot}.jpg"
        webp = OUT / f"{slot}.webp"
        # sips handles HEIC/PNG/JPEG; resample to 1600px on the long edge.
        subprocess.run(["sips", "-s", "format", "jpeg", "-s", "formatOptions", "80", "-Z", "1600", str(src), "--out", str(jpg)],
                       check=True, capture_output=True)
        subprocess.run(["cwebp", "-quiet", "-q", "78", str(jpg), "-o", str(webp)], check=True)
        found.append(slot)
        print(f"  {slot:13} <- {src.name}  ({webp.stat().st_size // 1024} KB webp)")

    entries = "\n".join(
        f'  "{s}": {{ webp: "/assets/photos/{s}.webp", jpg: "/assets/photos/{s}.jpg" }},' for s in found
    )
    MANIFEST.write_text(
        "// Install photos, by slot. Generated by scripts/import-photos.py from\n"
        '// "install-photos/" — don\'t edit by hand.\n'
        "// A slot that's missing falls back to the styled camera-feed panel.\n"
        "export type Photo = { webp: string; jpg: string };\n\n"
        'export const PHOTOS: Partial<Record<"hero" | "residential" | "commercial" | "construction" | "farm" | "solar-cam", Photo>> = {\n'
        + (entries + "\n" if entries else "")
        + "};\n"
    )
    print(f"{len(found)} photo(s) imported." if found else f"No photos found in {SRC}")


main()
