/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolarCamRouteImport } from './routes/solar-cam'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as IndustriesIndexRouteImport } from './routes/industries/index'
import { Route as IndustriesCommercialRouteImport } from './routes/industries/commercial'
import { Route as IndustriesConstructionRouteImport } from './routes/industries/construction'
import { Route as IndustriesFarmRouteImport } from './routes/industries/farm'
import { Route as IndustriesResidentialRouteImport } from './routes/industries/residential'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarCamRoute = SolarCamRouteImport.update({
  id: '/solar-cam',
  path: '/solar-cam',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesCommercialRoute = IndustriesCommercialRouteImport.update({
  id: '/industries/commercial',
  path: '/industries/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesConstructionRoute = IndustriesConstructionRouteImport.update({
  id: '/industries/construction',
  path: '/industries/construction',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesFarmRoute = IndustriesFarmRouteImport.update({
  id: '/industries/farm',
  path: '/industries/farm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesResidentialRoute = IndustriesResidentialRouteImport.update({
  id: '/industries/residential',
  path: '/industries/residential',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/quote': typeof QuoteRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar-cam': typeof SolarCamRoute
  '/api/chat': typeof ApiChatRoute
  '/industries/commercial': typeof IndustriesCommercialRoute
  '/industries/construction': typeof IndustriesConstructionRoute
  '/industries/farm': typeof IndustriesFarmRoute
  '/industries/residential': typeof IndustriesResidentialRoute
  '/industries/': typeof IndustriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/quote': typeof QuoteRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar-cam': typeof SolarCamRoute
  '/api/chat': typeof ApiChatRoute
  '/industries/commercial': typeof IndustriesCommercialRoute
  '/industries/construction': typeof IndustriesConstructionRoute
  '/industries/farm': typeof IndustriesFarmRoute
  '/industries/residential': typeof IndustriesResidentialRoute
  '/industries': typeof IndustriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/quote': typeof QuoteRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar-cam': typeof SolarCamRoute
  '/api/chat': typeof ApiChatRoute
  '/industries/commercial': typeof IndustriesCommercialRoute
  '/industries/construction': typeof IndustriesConstructionRoute
  '/industries/farm': typeof IndustriesFarmRoute
  '/industries/residential': typeof IndustriesResidentialRoute
  '/industries/': typeof IndustriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/products'
    | '/quote'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/solar-cam'
    | '/api/chat'
    | '/industries/commercial'
    | '/industries/construction'
    | '/industries/farm'
    | '/industries/residential'
    | '/industries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/products'
    | '/quote'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/solar-cam'
    | '/api/chat'
    | '/industries/commercial'
    | '/industries/construction'
    | '/industries/farm'
    | '/industries/residential'
    | '/industries'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/products'
    | '/quote'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/solar-cam'
    | '/api/chat'
    | '/industries/commercial'
    | '/industries/construction'
    | '/industries/farm'
    | '/industries/residential'
    | '/industries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  QuoteRoute: typeof QuoteRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolarCamRoute: typeof SolarCamRoute
  ApiChatRoute: typeof ApiChatRoute
  IndustriesCommercialRoute: typeof IndustriesCommercialRoute
  IndustriesConstructionRoute: typeof IndustriesConstructionRoute
  IndustriesFarmRoute: typeof IndustriesFarmRoute
  IndustriesResidentialRoute: typeof IndustriesResidentialRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar-cam': {
      id: '/solar-cam'
      path: '/solar-cam'
      fullPath: '/solar-cam'
      preLoaderRoute: typeof SolarCamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/commercial': {
      id: '/industries/commercial'
      path: '/industries/commercial'
      fullPath: '/industries/commercial'
      preLoaderRoute: typeof IndustriesCommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/construction': {
      id: '/industries/construction'
      path: '/industries/construction'
      fullPath: '/industries/construction'
      preLoaderRoute: typeof IndustriesConstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/farm': {
      id: '/industries/farm'
      path: '/industries/farm'
      fullPath: '/industries/farm'
      preLoaderRoute: typeof IndustriesFarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/residential': {
      id: '/industries/residential'
      path: '/industries/residential'
      fullPath: '/industries/residential'
      preLoaderRoute: typeof IndustriesResidentialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  QuoteRoute: QuoteRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolarCamRoute: SolarCamRoute,
  ApiChatRoute: ApiChatRoute,
  IndustriesCommercialRoute: IndustriesCommercialRoute,
  IndustriesConstructionRoute: IndustriesConstructionRoute,
  IndustriesFarmRoute: IndustriesFarmRoute,
  IndustriesResidentialRoute: IndustriesResidentialRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
